description = "ubi 8 base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.16.4"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base/build:0.0.1"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:0.0.1"
  run-image-mirrors = ["gcr.io/paketocommunity/run-ubi-base:0.0.1"]
